CREATE TABLE Link_Tag(
  ID_disciplina UNSIGNED INTEGER,
  ID_Tag UNSIGNED INTEGER,
)

CREATE TABLE Categorias(
  ID UNSIGNED INTEGER,
  Tag VARCHAR(200)
)

CREATE TABLE Recomendados(
  ID UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ID_origem_perfil INTEGER,
  ID_disciplina INTEGER,
  Ciclos INTEGER
)

CREATE TABLE Badge(
  ID UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  M1 INTEGER,
  M2 INTEGER,
  M3 INTEGER,
  M4 INTEGER
)


CREATE TABLE Feedback_Comment_DP(
  ID UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ID_origem_perfil UNSIGNED INTEGER,
  ID_destino UNSIGNED INTEGER,
  Estrelas INTEGER,
  Comentario VARCHAR(500)
)


CREATE TABLE Feedback_Comment_PF(
  ID UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ID_origem_perfil UNSIGNED INTEGER,
  ID_destino UNSIGNED INTEGER,
  LikeV INTEGER,
  Deslike INTEGER,
  Comentario VARCHAR(500)
)

CREATE TABLE Feedback_Ranked_Recomendations(
  ID UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ID_origem_perfil UNSIGNED INTEGER,
  ID_destino UNSIGNED INTEGER,
  Estrelas INTEGER
)

CREATE TABLE Disciplinas(
  ID UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nome VARCHAR(500),
  ID_Tag INTEGER
)

CREATE TABLE Perfil(
  ID UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nome VARCHAR(500),
  Badge_ID INT
)